# Generated by Django 2.0.13 on 2019-07-13 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marmita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=200)),
                ('Descrição', models.TextField()),
                ('Ingredientes', models.TextField()),
                ('Quantidade_estoque', models.IntegerField()),
                ('Ulr_image', models.CharField(max_length=200)),
                ('Preco', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Porcentagem', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
